# Generated by Django 6.0 on 2025-12-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='movieinfo',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='movieinfo',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='Year',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
